"""Art pass probe 62: OBJ import end-to-end + StaticMeshDescription API.

The OBJ path is the candidate production pipeline: geometry is generated as
text by Python (fully diff-able, no Blender, no third-party assets), then
imported as a real StaticMesh with UVs and material slots.
"""

import os
import traceback

import unreal

OUT = r'C:\Users\phanb\AppData\Local\Temp\opencode\kl\art62'
os.makedirs(OUT, exist_ok=True)
L = []


def p(m=''):
    L.append(str(m))
    unreal.log('A62: ' + str(m))


# --------------------------------------------------------------------------- #
# minimal OBJ + MTL writer
# --------------------------------------------------------------------------- #

def write_obj(path, mtl, name, verts, faces, uvs=None, normals=None):
    o = ['# generated by art_62_mesh.py', 'mtllib %s' % mtl, 'o %s' % name]
    for v in verts:
        o.append('v %.6f %.6f %.6f' % v)
    if normals:
        for n in normals:
            o.append('vn %.6f %.6f %.6f' % n)
    if uvs:
        for uv in uvs:
            o.append('vt %.6f %.6f' % uv)
    for f in faces:
        if uvs and normals:
            o.append('f ' + ' '.join('%d/%d/%d' % (i + 1, i + 1, i + 1) for i in f))
        elif uvs:
            o.append('f ' + ' '.join('%d/%d' % (i + 1, i + 1) for i in f))
        else:
            o.append('f ' + ' '.join('%d' % (i + 1) for i in f))
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(o) + '\n')


def make_box(x0, y0, z0, x1, y1, z1):
    v = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
         (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    uv = [(0, 0), (1, 0), (1, 1), (0, 1), (0, 0), (1, 0), (1, 1), (0, 1)]
    f = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
         (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    return v, f, uv


def main():
    eas = unreal.get_editor_subsystem(unreal.EditorAssetSubsystem)
    eas.make_directory('/Game/KhoangLang/ArtTest')
    at = unreal.AssetToolsHelpers.get_asset_tools()

    p('=== A. StaticMeshDescription API (class level, no asset needed) ===')
    SMD = getattr(unreal, 'StaticMeshDescription', None)
    if SMD is None:
        p('  unreal.StaticMeshDescription missing')
    else:
        ms = [m for m in dir(SMD) if not m.startswith('_')]
        p('  members (%d): %s' % (len(ms), ms))
        for m in ms:
            doc = (getattr(SMD, m).__doc__ or '').strip().replace('\r\n', ' ')
            if doc:
                p('    .%s -> %s' % (m, doc[:300]))
    p('  MeshDescriptionBase: %s' % hasattr(unreal, 'MeshDescriptionBase'))
    p('  SkeletalMeshDescription: %s' % hasattr(unreal, 'SkeletalMeshDescription'))

    p('')
    p('=== B. create StaticMesh without a factory ===')
    mpath = '/Game/KhoangLang/ArtTest/A62_SM'
    if unreal.load_asset(mpath):
        unreal.EditorAssetLibrary.delete_asset(mpath)
    sm = None
    try:
        sm = at.create_asset('A62_SM', '/Game/KhoangLang/ArtTest',
                             unreal.StaticMesh, None)
        p('  create_asset(None factory) -> %s' % (sm.get_name() if sm else None))
    except Exception as exc:
        p('  create_asset(None) -> %r' % str(exc)[:200])
    if sm is None:
        for fac in (unreal.StaticMeshFactory, ) if hasattr(unreal, 'StaticMeshFactory') else ():
            try:
                sm = at.create_asset('A62_SM', '/Game/KhoangLang/ArtTest',
                                     unreal.StaticMesh, fac)
                p('  created with %s' % fac)
            except Exception as exc:
                p('  %s -> %r' % (fac, str(exc)[:150]))

    if sm is not None:
        p('')
        p('=== C. author geometry into the description ===')
        try:
            md = sm.create_static_mesh_description()
            p('  md = %s [%s]' % (md, md.get_class().get_name()))
            p('  md members: %s' % [m for m in dir(md) if not m.startswith('_')])
            for m in [x for x in dir(md) if not x.startswith('_')]:
                doc = (getattr(md, m).__doc__ or '').strip().replace('\r\n', ' ')
                if doc:
                    p('    .%s -> %s' % (m, doc[:280]))
        except Exception as exc:
            p('  create_static_mesh_description -> %r' % str(exc)[:200])

    p('')
    p('=== D. OBJ import ===')
    obj = os.path.join(OUT, 'a62_box.obj')
    mtl = 'a62_box.mtl'
    v, f, uv = make_box(0, 0, 0, 100, 40, 220)
    with open(os.path.join(OUT, mtl), 'w', encoding='utf-8') as fh:
        fh.write('newmtl A62Mat\nKd 0.6 0.55 0.4\nKs 0.1 0.1 0.1\nd 1.0\n')
    write_obj(obj, mtl, 'a62_box', v, f, uv)
    p('  wrote obj: %d verts %d faces' % (len(v), len(f)))

    ipath = '/Game/KhoangLang/ArtTest/A62_Obj'
    if unreal.load_asset(ipath):
        unreal.EditorAssetLibrary.delete_asset(ipath)
    task = unreal.AssetImportTask()
    for prop, val in (('filename', obj),
                      ('destination_path', '/Game/KhoangLang/ArtTest'),
                      ('destination_name', 'A62_Obj'),
                      ('automated', True),
                      ('save', True),
                      ('replace_existing', True),
                      ('replace_existing_settings', True)):
        try:
            task.set_editor_property(prop, val)
        except Exception as exc:
            p('  task.%s -> %r' % (prop, str(exc)[:120]))
    at.import_asset_tasks([task])
    got = unreal.load_asset(ipath)
    p('  imported: %s [%s]' % (got.get_name() if got else None,
                               got.get_class().get_name() if got else '-'))
    if got:
        smi = unreal.get_editor_subsystem(unreal.StaticMeshEditorSubsystem)
        for fn, arg in (('get_number_verts', got), ('get_number_triangles', got),
                        ('get_number_sections', got), ('get_num_uv_channels', got),
                        ('get_number_materials', got)):
            try:
                p('  %s = %s' % (fn, getattr(smi, fn)(arg)))
            except Exception as exc:
                p('  %s -> %r' % (fn, str(exc)[:130]))
        try:
            bb = got.get_bounds()
            p('  bounds origin=%s extent=%s' % (bb.origin, bb.box_extent))
        except Exception as exc:
            p('  bounds -> %r' % str(exc)[:130])
        # re-import to prove the pipeline is repeatable
        p('  --- reimport to prove idempotency ---')
        t2 = unreal.AssetImportTask()
        t2.set_editor_property('filename', obj)
        t2.set_editor_property('destination_path', '/Game/KhoangLang/ArtTest')
        t2.set_editor_property('destination_name', 'A62_Obj')
        t2.set_editor_property('automated', True)
        t2.set_editor_property('replace_existing', True)
        at.import_asset_tasks([t2])
        again = unreal.load_asset(ipath)
        p('  reimport ok: %s' % (again is not None))

    p('')
    p('=== E. cleanup ===')
    for a in (mpath, ipath):
        if unreal.load_asset(a):
            try:
                unreal.EditorAssetLibrary.delete_asset(a)
                p('  deleted %s' % a)
            except Exception as exc:
                p('  delete %s: %r' % (a, str(exc)[:120]))
    p('DONE')


try:
    main()
except Exception:
    p(traceback.format_exc())
    p('A62_FATAL')
finally:
    with open(os.path.join(OUT, 'report.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(L) + '\n')
