"""Art pass probe 60: can Python author real static meshes headlessly?

Two candidate paths:
  A) StaticMesh.create_static_mesh_description() + build_from_static_mesh_descriptions
  B) write an .obj from Python and import it with AssetImportTask

Path B is the fallback that always works; if B imports a mesh with the expected
vertex/triangle count and UVs, the whole art pipeline can be built on it.
"""

import os
import traceback

import unreal

OUT = r'C:\Users\phanb\AppData\Local\Temp\opencode\kl\art60'
os.makedirs(OUT, exist_ok=True)
L = []


def p(m=''):
    line = str(m)
    L.append(line)
    unreal.log('A60: ' + line)


def dump(label, o, limit=4000):
    try:
        names = sorted(m for m in dir(o) if not m.startswith('_'))
    except Exception as exc:
        p('  %s: dir() -> %r' % (label, exc))
        return
    p('  %s (%d): %s' % (label, len(names), names))
    if len(names) > 0:
        for m in names:
            try:
                doc = (getattr(o, m).__doc__ or '').strip()
            except Exception:
                doc = ''
            if doc:
                p('      .%s -> %s' % (m, doc[:300].replace('\r\n', ' ')))


# --------------------------------------------------------------------------- #
# a procedural OBJ writer (no third-party library)
# --------------------------------------------------------------------------- #

def write_obj(path, name, verts, faces, uvs=None, normals=None):
    """verts: [(x,y,z)]; faces: [(i,j,k,...)]. uvs: per-face [(u,v)] or per-vertex."""
    L = ['# generated by art_60_mesh.py', 'mtllib %s.mtl' % name, 'o %s' % name]
    for v in verts:
        L.append('v %.6f %.6f %.6f' % v)
    if normals:
        for n in normals:
            L.append('vn %.6f %.6f %.6f' % n)
    if uvs:
        for uv in uvs:
            L.append('vt %.6f %.6f' % uv)
    for f in faces:
        if uvs and normals:
            L.append('f ' + ' '.join('%d/%d/%d' % (i + 1, i + 1, i + 1) for i in f))
        elif uvs:
            L.append('f ' + ' '.join('%d/%d' % (i + 1, i + 1) for i in f))
        else:
            L.append('f ' + ' '.join('%d' % (i + 1) for i in f))
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L) + '\n')
    return len(L)


OBJ = os.path.join(OUT, 'a60_test.obj')
# unit cube with a triangle on +Y so we can verify face count
CV = [(0, 0, 0), (100, 0, 0), (100, 100, 0), (0, 100, 0),
      (0, 0, 100), (100, 0, 100), (100, 100, 100), (0, 100, 100)]
CUV = [(0, 0), (1, 0), (1, 1), (0, 1)] * 2
CF = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
      (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]


def main():
    eas = unreal.get_editor_subsystem(unreal.EditorAssetSubsystem)
    eas.make_directory('/Game/KhoangLang/ArtTest')
    at = unreal.AssetToolsHelpers.get_asset_tools()

    p('=== A. relevant unreal symbols ===')
    names = [n for n in dir(unreal)]
    for key in ('MeshDescription', 'StaticMeshDescription', 'GeometryScript',
                'StaticMesh', 'MeshBuild', 'EditorStaticMeshLibrary'):
        hit = [n for n in names if key in n]
        p('  %-24s %s' % (key, hit[:24]))

    p('')
    p('=== B. create a StaticMesh asset + description ===')
    mpath = '/Game/KhoangLang/ArtTest/A60_SM'
    if unreal.load_asset(mpath):
        unreal.EditorAssetLibrary.delete_asset(mpath)
    sm = at.create_asset('A60_SM', '/Game/KhoangLang/ArtTest',
                         unreal.StaticMesh, unreal.StaticMeshFactoryNew())
    p('  created: %s' % (sm.get_name() if sm else None))
    dump('StaticMesh methods', unreal.StaticMesh)

    md = None
    for call in ('create_static_mesh_description', 'get_static_mesh_description'):
        try:
            md = getattr(sm, call)()
            p('  %s() -> %s' % (call, md))
            if md is not None:
                p('     class = %s' % md.get_class().get_name())
                dump('desc.%s' % call, md)
            break
        except Exception as exc:
            p('  %s() -> %r' % (call, str(exc)[:200]))
    p('  has mesh desc: %s' % (md is not None))
    p('  StaticMeshDescription symbol: %s' % hasattr(unreal, 'StaticMeshDescription'))

    p('')
    p('=== C. try to author a box through the description ===')
    if md is not None:
        for attempt in ('create_vertex', 'add_vertex', 'AddVertex'):
            fn = getattr(md, attempt, None)
            if fn is None:
                continue
            try:
                r = fn(unreal.Vector(0, 0, 0))
                p('  %s(Vector) -> %r' % (attempt, r))
                break
            except Exception as exc:
                p('  %s(Vector) -> %r' % (attempt, str(exc)[:160]))
        for attempt in ('create_polygon', 'add_polygon', 'AddPolygon'):
            fn = getattr(md, attempt, None)
            if fn is None:
                continue
            try:
                p('  %s() doc = %s' % (attempt, (fn.__doc__ or '')[:200]
                                        .replace('\r\n', ' ')))
            except Exception as exc:
                p('  %s -> %r' % (attempt, str(exc)[:120]))

    p('')
    p('=== D. OBJ import path ===')
    n = write_obj(OBJ, 'a60_test', CV, CF, CUV)
    p('  wrote %s (%d lines)' % (OBJ, n))
    ipath = '/Game/KhoangLang/ArtTest/A60_Obj'
    if unreal.load_asset(ipath):
        unreal.EditorAssetLibrary.delete_asset(ipath)
    task = unreal.AssetImportTask()
    task.set_editor_property('filename', OBJ)
    task.set_editor_property('destination_path', '/Game/KhoangLang/ArtTest')
    task.set_editor_property('destination_name', 'A60_Obj')
    task.set_editor_property('automated', True)
    task.set_editor_property('save', True)
    task.set_editor_property('replace_existing', True)
    task.set_editor_property('replace_existing_settings', True)
    at.import_asset_tasks([task])
    got = unreal.load_asset(ipath)
    p('  imported: %s [%s]' % (got.get_name() if got else None,
                               got.get_class().get_name() if got else '-'))
    if got:
        smi = unreal.get_editor_subsystem(unreal.StaticMeshEditorSubsystem)
        p('  verts=%s tris=%s sections=%s uv0=%s lods=%s' % (
            smi.get_number_verts(got) if smi else '?',
            smi.get_number_triangles(got) if smi else '?',
            smi.get_number_sections(got) if smi else '?',
            smi.get_num_uv_channels(got) if smi else '?',
            got.get_num_lods() if hasattr(got, 'get_num_lods') else '?'))
        bb = got.get_bounds()
        p('  bounds origin=%s extent=%s' % (bb.origin, bb.box_extent))
        p('  material slots: %s' % smi.get_number_materials(got))
        for prop, val in (('light_map_resolution_scale', 1.0),
                          ('lightmap_coord_index', 0),
                          ('light_map_coordinate_index', 0)):
            try:
                got.set_editor_property(prop, val)
                p('    %s ok' % prop)
            except Exception:
                pass

    p('')
    p('=== E. Interchange / FBX surface ===')
    for n2 in ('InterchangeGenericAssetsPipeline', 'InterchangeGenericCommonSkeletalMeshesAndAnimationsProperties',
               'FbxImportUI', 'FbxStaticMeshImportData', 'InterchangePipelineBaseOverride'):
        p('  unreal.%-58s %s' % (n2, hasattr(unreal, n2)))
    for n2 in ('import_asset', 'import_assets', 'get_interchange_manager'):
        o = getattr(eas, n2, None)
        p('  EditorAssetSubsystem.%-16s %s' % (n2, o is not None))
    p('  unreal.AssetImportTask fields: %s' % (
        [m for m in dir(unreal.AssetImportTask()) if not m.startswith('_')],))

    p('')
    p('=== F. cleanup ===')
    for a in (mpath, ipath):
        if unreal.load_asset(a):
            try:
                unreal.EditorAssetLibrary.delete_asset(a)
                p('  deleted %s' % a)
            except Exception as exc:
                p('  delete %s: %r' % (a, exc))
    with open(os.path.join(OUT, 'report.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(L) + '\n')
    p('DONE')


try:
    main()
except Exception:
    p(traceback.format_exc())
    p('A60_FATAL')
    with open(os.path.join(OUT, 'report.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(L) + '\n')
